sonar.projectKey=msm-oc-projects_msm-projet-07-fullstack
sonar.organization=msm-oc-projects
sonar.projectName=Orion MicroCRM

sonar.sources=back/src/main/java,front/src/app
sonar.tests=back/src/test/java,front/src/app
sonar.test.inclusions=back/src/test/**/*.java,front/src/**/*.spec.ts
sonar.exclusions=front/node_modules/**,front/dist/**,back/build/**,misc/**

sonar.java.binaries=back/build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info
