input {
  tcp {
    port => 5000
    codec => json_lines
  }

  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "application" => "orion-microcrm"
      "environment" => "local"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orion-microcrm-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
